Smoke test job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -27,16 +27,13 @@ commands:
           name: Revert migrations
           when: on_fail
           command: |
-            cd backend
-            npm install
-            npm run migrations:revert
-            # SUCCESS= curl -H "token: <<parameters.workflow_id>>" --request GET https://api.memstash.io/values/migration-<<parameters.workflow_id>>
-            # if(( $SUCCESS==1 )); 
-            # then
-            #  backend
-            #  npm install
-            #  npm run migrations:revert
-            # fi
+            SUCCESS=curl -H "token: <<parameters.workflow_id>>" --request GET https://api.memstash.io/values/migration-<<parameters.workflow_id>>
+            if(( $SUCCESS==1 )); 
+            then
+             cd backend
+             npm install
+             npm run migrations:revert
+            fi
             
 jobs:
   build-frontend:
@@ -354,13 +351,13 @@ jobs:
           command: |
             echo "${API_URL}"
             ENDPOINT="https://${API_URL}/api/status/"
-            if curl -s ${ENDPOINT} | grep "ok"
-            then
-              echo "Backend Smoke Test Successful"
-            else
-              echo "Backend Smoke Test Failed"
-              exit 1
-            fi
+            # if curl -s ${ENDPOINT} | grep "ok"
+            # then
+            #   echo "Backend Smoke Test Successful"
+            # else
+            #   echo "Backend Smoke Test Failed"
+            #   exit 1
+            # fi
             
       - run:
           name: Frontend smoke test.
@@ -369,10 +366,8 @@ jobs:
             echo ${URL}
             if curl -s ${URL} | grep "Welcome"
             then
-              echo "Frontend Smoke Test Successfull"
               exit 1
             else
-              echo "Frontend Smoke Test Failed"
               exit 1
             fi
       - destroy-environment:
