Smoke Tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -27,19 +27,19 @@ commands:
           name: Revert migrations
           when: on_fail
           command: |
-            # cd backend
-            # npm install
-            # npm run migrations:revert
-            SUCCESS=$(curl -H "token: <<parameters.workflow_id>>" --request GET https://api.memstash.io/values/migration-<<parameters.workflow_id>>)
-            echo "${SUCCESS}"
-            if[[ "${SUCCESS}" == 1 ]]; 
-            then
-             cd backend
-             npm install
-             npm run migrations:revert
-            else
-             echo "no migrations to revert" 
-            fi
+            cd backend
+            npm install
+            npm run migrations:revert
+            # SUCCESS=$(curl -H "token: <<parameters.workflow_id>>" --request GET https://api.memstash.io/values/migration-<<parameters.workflow_id>>)
+            # echo "${SUCCESS}"
+            # if["${SUCCESS}" == 1]; 
+            # then
+            #  cd backend
+            #  npm install
+            #  npm run migrations:revert
+            # else
+            #  echo "no migrations to revert" 
+            # fi
             
 jobs:
   build-frontend:
@@ -346,16 +346,11 @@ jobs:
             pip install awscli
             
       - run:
-          name: Get backend url
+          name: Get backend url and smoke test
           command: |
             export BACKEND_IP=$(curl -H "token: ${CIRCLE_WORKFLOW_ID:0:7}" \
               --request GET https://api.memstash.io/values/backendurl)
             export API_URL="http://${BACKEND_IP}:3030"
-            echo "${API_URL}"
-                     
-      - run:
-          name: Backend smoke test.
-          command: |
             echo "${API_URL}"
             export ENDPOINT="${API_URL}/api/status"
             echo "${ENDPOINT}"
@@ -366,6 +361,20 @@ jobs:
               echo "Backend Smoke Test Failed"
               exit 1
             fi
+                     
+      # - run:
+      #     name: Backend smoke test.
+      #     command: |
+      #       echo "${API_URL}"
+      #       # export ENDPOINT="${API_URL}/api/status"
+      #       # echo "${ENDPOINT}"
+      #       # if curl -s "${ENDPOINT}" | grep "ok"
+      #       # then
+      #       #   echo "Backend Smoke Test Successful"
+      #       # else
+      #       #   echo "Backend Smoke Test Failed"
+      #       #   exit 1
+      #       # fi
             
       - run:
           name: Frontend smoke test.
