Smoke Test Job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -27,13 +27,16 @@ commands:
           name: Revert migrations
           when: on_fail
           command: |
-            SUCCESS=curl -H "token: <<parameters.workflow_id>>" --request GET https://api.memstash.io/values/migration-<<parameters.workflow_id>>
-            if(( $SUCCESS==1 )); 
-            then
-             cd backend
-             npm install
-             npm run migrations:revert
-            fi
+            cd backend
+            npm install
+            npm run migrations:revert
+            # SUCCESS=$(curl -H "token: <<parameters.workflow_id>>" --request GET https://api.memstash.io/values/migration-<<parameters.workflow_id>>)
+            # if(( $SUCCESS==1 )); 
+            # then
+            #  cd backend
+            #  npm install
+            #  npm run migrations:revert
+            # fi
             
 jobs:
   build-frontend:
@@ -346,6 +349,15 @@ jobs:
               --request GET https://api.memstash.io/values/backendurl)
             export API_URL="http://${BACKEND_IP}:3030"
             echo "${API_URL}"
+            export ENDPOINT=$("https://${API_URL}/api/status")
+            echo "${ENDPOINT}"
+            if curl -s ${ENDPOINT} | grep "ok"
+            then
+              echo "Backend Smoke Test Successful"
+            else
+              echo "Backend Smoke Test Failed"
+              exit 1
+            fi
       - run:
           name: Backend smoke test.
           command: |
